name: Android CI

on:
  push:
    branches: [ "kt-rewrite" ]
  pull_request:
    branches: [ "kt-rewrite" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Give permission to executable
        run: chmod +x gradlew

      - name: Clear build cache
        uses: gradle/gradle-build-action@v3.1.0
        with:
          gradle-version: nightly
          arguments: clean

      - name: Build APK with Gradle
        run: ./gradlew assembleDebug

      - name: Upload Full Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug
