name: Release CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        
      - name: Install Android Build Tools
        run: sdkmanager "build-tools;29.0.3"

      - name: Give permission to executable
        run: chmod +x gradlew

      - name: Clear build cache
        uses: gradle/gradle-build-action@v3.1.0
        with:
          gradle-version: nightly
          arguments: clean

      - name: Build Lite Release APK
        run: ./gradlew assembleLiteRelease

      - name: Sign Lite Variant APKs
        uses: r0adkll/sign-android-release@v1
        id: sign_app_lite
        with:
          releaseDirectory: app/build/outputs/apk/lite/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Signed Lite Release APK
        uses: actions/upload-artifact@v3
        with:
          name: lite-release-apk
          path: app/build/outputs/apk/lite/release/*.apk
